name: release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        arch: ["", "-arm"]
    runs-on: ${{ matrix.os }}${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build -t ghcr.io/kfox1111/cid2pid:${{github.ref_name}}-$(uname -i)
          docker push -t ghcr.io/kfox1111/cid2pid:${{github.ref_name}}-$(uname -i)
  manifest:
    runs-on: ubuntu-24.0.4
    needs: build
    steps:
      - run: |
          docker manifest create ghcr.io/kfox1111/cid2pid:${{github.ref_name}} \
            --amend ghcr.io/kfox1111/cid2pid:${{github.ref_name}}-x86_64 \
            --amend ghcr.io/kfox1111/cid2pid:${{github.ref_name}}-aarch64 && \
          docker manifest push ghcr.io/kfox1111/cid2pid:${{github.ref_name}}
