name: test
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        arch: ["", "-arm"]
    runs-on: ${{ matrix.os }}${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: uname -i && docker build -t test .
